language: python
jobs:
  include:
    - dist: trusty
      python: "2.6"
    - python: "2.7"
    - python: "3.4"
    - python: "3.5"
    - python: "3.6"
    - python: "3.7"
    - python: "3.8"
    - python: "pypy"
cache: pip
install:
    - pip install attrs==18.2.0 pytest-cov requests
script:
    - ./ci/test.sh && ./ci/test-integration.sh
